name: Publish Python to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry install

      - name: Build the package
        run: poetry build

      - name: Publish to TestPyPI with Trusted Publisher
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/